language: ruby
rvm:
- 2.4.2
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  app: rocky-everglades-35483
  run:
  - "rails db:migrate"
  api_key:
    secure: DX3LFZxKT61UzmpYnAgXgpjo17I5lgODOrZVmxC7mvZPcDh4LrHknyWkxHaW8x8J80Afg91WOUk9oj4zr8OVVSirsb1TcJAwNCa5oX/x+0+WuASdRswUGuiCGkRc4CxK7/o2gw7NyHx3eMwKoXAdw7C0VwiiuiKvJona7CbDDZz3LRc0+a34bacM4O8icKs7ZVxpDjO9wpqtATKFFZiq5y4yHTKprofGg6kCS3HzW6kCe6jFdrW//LrGPzyYFcVSW11auGRuQSQShZ6S/gKjtixUNEiibfK+FTa9oyue4urYh34d0OBpBiqT0wRzrSscpeVwXrpG0bQIN0OHMdvtTI1gC7kFAw18/Eoapr+/HOqpQaTA3chXylkr+I/5ItGOOALdPwz+z3ZRO9XbpPXGs89e4/0MH3ejd77dp2GmD8Im3d/EKpuNp5RZ9aTMDeFa418sf9q6eEzZRV3dnSDzfwoMius76OXb64FUlh1d/pmrx79Znl51NfIdXCs7ZYZz0VOi351LMD61aWKB7RP3EAfMo8FaEw8zH+qT5og2L37IHbuvK/sMUtWlxImn6OfnzUWZWw0XaEmk7gqJN8uqZNxhdXRijl17cQy0emtA3Ekr3xW06fp96c3hoe4jE38GcZhww0hEFRfXcjLU8lnxSc3F7bM0/B8aa+PEoCC/UaU=
