language: ruby
rvm:
- 2.4.2
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  app: rocky-everglades-35483
  run:
  - rails db:migrate
  api_key:
    secure: UfXzZ7nKhbvKWPUfSaazwUXAVsrj89sieadHdCIV3P+LSrRKC7xvAsRhTmvXcENZmKNwy/by+dj8DnCLO10tMJ7LgCdc76f/vduZ3NKWUgpgG85qnPZ+iqai+Ghf1JZaoy2un37qlGa/iJBlgQzSqJRcOhGamS6tm96CwlyIxCrX31qti1EqhnnEwz1sc0PMD8EFsWz8Qd7JM68obstfJZxq9B9mPPVUUsVXDKC8RkFdhlgq//lU2/IWASwXMJBzEYC+vPoSx0+lquhmTNzzGkSTmgFlceDfRGn6EWD7ibzK4UivytgjtYndDXKbpR5ZdhLogn8twfa7dBuCA84Nfgmw1W5ORO5ul1HaOXPEhNSTydF1KJw7e2SDfb1uLp5Z2yQXzaeuPks/wThHaOemU0agvH5BG/rBZGGCBBwJe9MHIj+KmCY1rViUo4jibdiHlYEEhzqOQ6Zg1/CxHePjav0hcFf6RagOeIa15zwD7E+AT6LEHZ9wMQIOsFNm29WuS6EIYt4kPl0zPHSj3X0bDCjkJF7Vra9DyGv/kmLCa+QTqTxw8/9mc/YNdFC7CPmZA+7FaQdeqmoBxrPCikfhQ1xL81ummv8EDtiYpsMAFoq5+4ge2vrzU+Dm/FVhBQjVEeg7HQtUqHfq8H3HDDEkj7JkR7c5MdDNW3oeESsSMOI=
